name: Deploy Schema via Jenkins

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag (e.g., v1.0.0)"
        required: true
      db_name:
        description: "PostgreSQL database name"
        required: true
      available_schemas:
        description: "Available schemas to deploy (comma-separated)"
        required: true

jobs:
  trigger-jenkins-deployment:
    name: Trigger Jenkins Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trigger Jenkins Job
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_JOB: Schema-Deploy
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        run: |
          echo "Triggering Jenkins job for TAG=${{ inputs.image_tag }} on DB=${{ inputs.db_name }}"

          curl -X POST "$JENKINS_URL/job/$JENKINS_JOB/buildWithParameters" \
            --user "$JENKINS_USER:$JENKINS_API_TOKEN" \
            --data-urlencode "TAG=${{ inputs.image_tag }}" \
            --data-urlencode "POSTGRES_DB=${{ inputs.db_name }}" \
            --data-urlencode "AVAILABLE_SCHEMAS=${{ inputs.available_schemas }}" \
            --data-urlencode "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" \
            --data-urlencode "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" \
            --data-urlencode "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" \
            --data-urlencode "EMAIL_APP_PASSCODE=${{ secrets.EMAIL_APP_PASSCODE }}" \
            --data-urlencode "CONTAINER_NAME=schema-manager" \
            --fail

      - name: ✅ Success Message
        run: echo "Jenkins job triggered successfully for image_tag=${{ inputs.image_tag }} and db=${{ inputs.db_name }}"


CRUMB=$(curl -u "admin:853aeda36d014bb6a5978ef35cf6a2c2" "http://13.203.206.90:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")
curl -u admin:853aeda36d014bb6a5978ef35cf6a2c2 http://13.203.206.90:8080/crumbIssuer/api/json
curl -X POST "http://13.203.206.90:8080/job/Schema-Deploy/buildWithParameters" \
    --user "admin:853aeda36d014bb6a5978ef35cf6a2c2" \
    -H "$CRUMB" \
    --data-urlencode "TAG=v1.0.0" \
    --data-urlencode "POSTGRES_DB=merchant_db" \
    --data-urlencode "AVAILABLE_SCHEMAS=postgres/merchant_template" \
    --data-urlencode "POSTGRES_HOST=13.203.206.90" \
    --data-urlencode "POSTGRES_PASSWORD=Admin123" \
    --data-urlencode "POSTGRES_USER=admin" \
    --data-urlencode "EMAIL_APP_PASSCODE=***" \
    --data-urlencode "CONTAINER_NAME=schema-manager" \
    --fail

